### ISSUE TITLE
Error during compilation after Gradle migration

### ISSUE THREAD

**Issue by mregnauld** [marcellocamara/sensitive_clipboard#1] opened 2024-02-23 18:55 UTC
In my project, targeting Android and iOS, I implemented the `sensitive_clipboard` library.

Now, since there were some changes in Gradle, we need to [migrate some code](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply).

But then, when I try to rebuild my app, I got the following error during compilation:

```
'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
```

As soon as I remove the `sensitive_clipboard` dependency, the error disappears.

**Comment by marcellocamara** [comment] 2024-02-23 22:09
I saw that you opened a similar issue [here](https://github.com/googleads/googleads-mobile-flutter/issues/1010).
You're using jdk 17. I didn't upgraded and I'm also using google_mobile_ads on another projects. Jdk 11 is working fine.

I'm using  `Flutter 3.19.1` with `Dart 3.3.0`, with this packages that you're using, and the problem is not reproducible.

Seems like you have an environment problem, not related to libraries.

**Comment by mregnauld** [comment] 2024-02-25 10:06
OK so here is a [sample project](https://github.com/mregnauld/sensitive_clipboard_error) I made, that I tried to compile using JDK 11 and Flutter 3.19.1 as you mentioned (I also added `google_mobile_ads`, and the project worked fine before I added your package).

Even though I `flutter clean` and `flutter pub get` multiple times, I keep having the following error:

```
Inconsistent JVM-target compatibility detected for tasks 'compileDebugJavaWithJavac' (1.8) and 'compileDebugKotlin' (17).
```

As soon as I comment `sensitive_clipboard: ^1.0.0` in my pubspec.yaml, everything works fine again.

Could you try on your end and see if you have the same error?

Thanks.

**Comment by marcellocamara** [comment] 2024-02-25 15:16
@mregnauld, your sample project is not a flutter project.

I've updated only the example app, at the sensitive_clipboard project folder, and it works perfectly.
As I told, seems like you have an environment problem. Not configuring correctly.

Try to run the **example** app at the `sensitive_clipboard` using the **update-example branch**: https://github.com/marcellocamara/sensitive_clipboard/tree/update-example

Evidence:
![sensitive_clipboard with new example app](https://github.com/marcellocamara/sensitive_clipboard/assets/18273071/5c556933-460b-4d6f-9cfa-ec4e1fc29be4)

Notice that I've only updated the example app, using the migration guide that you told: https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply
No changes at the plugin. It's still working.

Additional info:
Notice that I've updated only the example app, and this build red flags ***is gone***:
```
You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release.
Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply
```

**Comment by mregnauld** [comment] 2024-02-25 19:09
My bad, I made a mistake, I just updated my project, now you have the full [sample project](https://github.com/mregnauld/sensitive_clipboard_error).
I'll take a look at your feedback.

**Comment by marcellocamara** [comment] 2024-02-25 19:41
@mregnauld , I've made some changes into your project, and it's working without any changes at this plugin.

Evidence:
![done](https://github.com/marcellocamara/sensitive_clipboard/assets/18273071/4d7c8c2f-43a3-4677-a964-dd3b1dc68267)

Changes to fix your project: https://github.com/mregnauld/sensitive_clipboard_error/pull/1

Explanation:
I only refactor all native side with default flutter project files. It's working, and demonstrate that plugins has nothing with it.
I'll be closing this issue like it is environment/project settings problem. 
Ok?

**Closed as completed by marcellocamara** 2024-02-25 19:41 UTC

**Comment by mregnauld** [comment] 2024-02-25 20:09
OK!
Thank you very much for your time!
